[project]
name="Mood"
description="Multi-user dungeon, client and server"
version="0.1.0"
requires-python = ">=3.12"
dependencies = ["python-cowsay"]

[build-system]
requires = ["setuptools", "Sphinx", "build", "doit", "python-cowsay"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
mood="mood"

[tool.setuptools.package-data]
mood=["po/*/*/*.mo", "_build/*", "mood/client/*.py", "mood/server/*.py"]

[project.scripts]
client = "mood.client.__main__:run_client"
server = "mood.server.__main__:run_server"

